name: CI/CD
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - .idea
      - .editorconfig
      - .gitattributes
      - .gitignore
      - LICENSE
      - README.md
  push:
    branches:
      - master
    paths-ignore:
      - .idea
      - .editorconfig
      - .gitattributes
      - .gitignore
      - LICENSE
      - README.md
jobs:
  ci:
    name: "CI"
    runs-on: ${{ matrix.os }}
    steps:
      - name: "Инициализация рабочего процесса"
        uses: actions/checkout@v4
      - name: "Подготовка JDK"
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          java-package: jdk+fx
      - name: "Подготовка Gradle"
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: "8.10"
      - name: "Сборка и тестирование проекта"
        run: gradle test
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
#  cd:
#    name: "CD"
#    needs: ci
#    runs-on: ${{ matrix.os }}
#    steps:
#      - name: "Инициализация рабочего процесса"
#        uses: actions/checkout@v4
#      - name: "Подготовка JDK"
#        uses: actions/setup-java@v4
#        with:
#          java-version: 21
#          distribution: temurin
#          java-package: jdk+fx
#      - name: "Подготовка Gradle"
#        uses: gradle/actions/setup-gradle@v4
#        with:
#          gradle-version: "8.10"
#      - name: "Сборка и публикация проекта"
#        env:
#          OSSRH_CREDENTIALS_USERNAME: ${{ secrets.OSSRH_CREDENTIALS_USERNAME }}
#          OSSRH_CREDENTIALS_PASSWORD: ${{ secrets.OSSRH_CREDENTIALS_PASSWORD }}
#          SINGING_KEY_ID: ${{ secrets.SINGING_KEY_ID }}
#          SINGING_KEY_PASSWORD: ${{ secrets.SINGING_KEY_PASSWORD }}
#          SINGING_KEY_SECRET: ${{ secrets.SINGING_KEY_SECRET }}
#        run: gradle publish
#    strategy:
#      matrix:
#        os: [ ubuntu-latest, macos-latest, windows-latest ]
